services:
    forum.post.manager:
        class: Forum\ForumBundle\Manager\PostManager
        arguments: [@service_container]

    forum.thread.manager:
        class: Forum\ForumBundle\Manager\ThreadManager
        arguments: [@service_container]
